defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"
      ignore_conflicts: true
      label_conflicts: A:backport/conflict

pull_request_rules:
  - name: backport marked changes to release/v3.x
    conditions:
      - base=main
      - label=A:backport/v3.x
    actions:
      backport:
        branches:
          - release/v3.x

  - name: backport marked changes to release/v4.0.x
    conditions:
      - base=main
      - label=A:backport/v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x

  - name: backport marked changes to release/v5.0.x
    conditions:
      - base=main
      - label=A:backport/v5.0.x
    actions:
      backport:
        branches:
          - release/v5.0.x
