//go:build halo2

package halo2

import (
	"encoding/binary"
	"os"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/z-cale/zally/crypto/zkp"
)

// TestGenerateShareRevealRoundTrip generates a share reveal proof and verifies it.
//
// This test requires the halo2 build tag and the Rust static library:
//
//	make circuits
//	go test -tags halo2 -count=1 -v ./crypto/zkp/halo2/ -run TestGenerateShareRevealRoundTrip
//
// The test reads inputs from a fixture file generated by the Rust fixture
// generator (cargo test --release -- generate_fixtures --ignored).
// Proof generation takes ~30-60s in release mode.
func TestGenerateShareRevealRoundTrip(t *testing.T) {
	// Read fixture file.
	// Format (2384 bytes):
	//   [0..772)       merkle_path
	//   [772..1796)    all_enc_shares (1024 bytes: 16 × (C1+C2) × 32 bytes)
	//   [1796..2308)   share_blinds (512 bytes: 16 × 32-byte blind factors)
	//   [2308..2312)   share_index (u32 LE)
	//   [2312..2316)   proposal_id (u32 LE)
	//   [2316..2320)   vote_decision (u32 LE)
	//   [2320..2352)   round_id (32 bytes)
	//   [2352..2384)   shares_hash (32 bytes)
	fixture, err := os.ReadFile("../testdata/share_reveal_inputs.bin")
	require.NoError(t, err, "fixture file missing — run: make fixtures")
	require.Len(t, fixture, 2384, "unexpected fixture size")

	merklePath := fixture[0:772]

	var allEncShares [32][32]byte
	for i := 0; i < 32; i++ {
		copy(allEncShares[i][:], fixture[772+i*32:772+(i+1)*32])
	}

	var shareBlinds [16][32]byte
	for i := 0; i < 16; i++ {
		copy(shareBlinds[i][:], fixture[1796+i*32:1796+(i+1)*32])
	}

	shareIndex := binary.LittleEndian.Uint32(fixture[2308:2312])
	proposalID := binary.LittleEndian.Uint32(fixture[2312:2316])
	voteDecision := binary.LittleEndian.Uint32(fixture[2316:2320])

	var roundID [32]byte
	copy(roundID[:], fixture[2320:2352])

	var sharesHash [32]byte
	copy(sharesHash[:], fixture[2352:2384])

	// Generate proof.
	t.Log("generating share reveal proof (this takes ~30-60s)...")
	proof, nullifier, treeRoot, err := GenerateShareRevealProof(
		merklePath,
		allEncShares,
		shareBlinds,
		shareIndex,
		proposalID, voteDecision,
		roundID,
		sharesHash,
	)
	require.NoError(t, err)
	require.NotEmpty(t, proof)

	t.Logf("proof: %d bytes, nullifier: %x..., treeRoot: %x...",
		len(proof), nullifier[:4], treeRoot[:4])

	// Verify the generated proof using the verify FFI.
	// Build EncShare: C1 || C2 from allEncShares at shareIndex.
	idx := int(shareIndex)
	encShare := make([]byte, 64)
	copy(encShare[:32], allEncShares[idx*2][:])
	copy(encShare[32:], allEncShares[idx*2+1][:])

	inputs := zkp.VoteShareInputs{
		ShareNullifier:   nullifier[:],
		EncShare:         encShare,
		ProposalId:       proposalID,
		VoteDecision:     voteDecision,
		VoteRoundId:      roundID[:],
		VoteCommTreeRoot: treeRoot[:],
	}

	err = VerifyShareRevealProof(proof, inputs)
	require.NoError(t, err, "generated proof should verify")
}
