// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zvote/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SetupVoteRound_FullMethodName       = "/zvote.v1.Msg/SetupVoteRound"
	Msg_RegisterDelegation_FullMethodName   = "/zvote.v1.Msg/RegisterDelegation"
	Msg_CreateVoteCommitment_FullMethodName = "/zvote.v1.Msg/CreateVoteCommitment"
	Msg_RevealVoteShare_FullMethodName      = "/zvote.v1.Msg/RevealVoteShare"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the vote module's Msg service.
// NOTE: This service is NOT annotated with cosmos.msg.v1.service because vote
// transactions use ZKP + RedPallas authentication instead of standard Cosmos
// signatures. In Phase 5, transaction submission bypasses the Cosmos Tx envelope
// entirely; the Msg service is defined here for gRPC registration only.
type MsgClient interface {
	SetupVoteRound(ctx context.Context, in *MsgSetupVoteRound, opts ...grpc.CallOption) (*MsgSetupVoteRoundResponse, error)
	RegisterDelegation(ctx context.Context, in *MsgRegisterDelegation, opts ...grpc.CallOption) (*MsgRegisterDelegationResponse, error)
	CreateVoteCommitment(ctx context.Context, in *MsgCreateVoteCommitment, opts ...grpc.CallOption) (*MsgCreateVoteCommitmentResponse, error)
	RevealVoteShare(ctx context.Context, in *MsgRevealVoteShare, opts ...grpc.CallOption) (*MsgRevealVoteShareResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetupVoteRound(ctx context.Context, in *MsgSetupVoteRound, opts ...grpc.CallOption) (*MsgSetupVoteRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetupVoteRoundResponse)
	err := c.cc.Invoke(ctx, Msg_SetupVoteRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterDelegation(ctx context.Context, in *MsgRegisterDelegation, opts ...grpc.CallOption) (*MsgRegisterDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterDelegationResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateVoteCommitment(ctx context.Context, in *MsgCreateVoteCommitment, opts ...grpc.CallOption) (*MsgCreateVoteCommitmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateVoteCommitmentResponse)
	err := c.cc.Invoke(ctx, Msg_CreateVoteCommitment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealVoteShare(ctx context.Context, in *MsgRevealVoteShare, opts ...grpc.CallOption) (*MsgRevealVoteShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealVoteShareResponse)
	err := c.cc.Invoke(ctx, Msg_RevealVoteShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the vote module's Msg service.
// NOTE: This service is NOT annotated with cosmos.msg.v1.service because vote
// transactions use ZKP + RedPallas authentication instead of standard Cosmos
// signatures. In Phase 5, transaction submission bypasses the Cosmos Tx envelope
// entirely; the Msg service is defined here for gRPC registration only.
type MsgServer interface {
	SetupVoteRound(context.Context, *MsgSetupVoteRound) (*MsgSetupVoteRoundResponse, error)
	RegisterDelegation(context.Context, *MsgRegisterDelegation) (*MsgRegisterDelegationResponse, error)
	CreateVoteCommitment(context.Context, *MsgCreateVoteCommitment) (*MsgCreateVoteCommitmentResponse, error)
	RevealVoteShare(context.Context, *MsgRevealVoteShare) (*MsgRevealVoteShareResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SetupVoteRound(context.Context, *MsgSetupVoteRound) (*MsgSetupVoteRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupVoteRound not implemented")
}
func (UnimplementedMsgServer) RegisterDelegation(context.Context, *MsgRegisterDelegation) (*MsgRegisterDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDelegation not implemented")
}
func (UnimplementedMsgServer) CreateVoteCommitment(context.Context, *MsgCreateVoteCommitment) (*MsgCreateVoteCommitmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVoteCommitment not implemented")
}
func (UnimplementedMsgServer) RevealVoteShare(context.Context, *MsgRevealVoteShare) (*MsgRevealVoteShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealVoteShare not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SetupVoteRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetupVoteRound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetupVoteRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetupVoteRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetupVoteRound(ctx, req.(*MsgSetupVoteRound))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDelegation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDelegation(ctx, req.(*MsgRegisterDelegation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateVoteCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVoteCommitment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVoteCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateVoteCommitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVoteCommitment(ctx, req.(*MsgCreateVoteCommitment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealVoteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealVoteShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealVoteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealVoteShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealVoteShare(ctx, req.(*MsgRevealVoteShare))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zvote.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupVoteRound",
			Handler:    _Msg_SetupVoteRound_Handler,
		},
		{
			MethodName: "RegisterDelegation",
			Handler:    _Msg_RegisterDelegation_Handler,
		},
		{
			MethodName: "CreateVoteCommitment",
			Handler:    _Msg_CreateVoteCommitment_Handler,
		},
		{
			MethodName: "RevealVoteShare",
			Handler:    _Msg_RevealVoteShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvote/v1/tx.proto",
}
