/**
 * Shared helpers for Zally API tests.
 *
 * - BASE_URL: the Cosmos SDK API server (default http://localhost:1317)
 * - deriveRoundId: replicates the on-chain Blake2b-256 round ID derivation
 * - makeCreateVotingSessionPayload / makeDelegateVotePayload: build valid JSON bodies
 * - getRealProofFixtures: loads real Halo2 toy proof + public input from disk
 */

import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { blake2b } from "@noble/hashes/blake2b";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export const BASE_URL = process.env.ZALLY_API_URL ?? "http://localhost:1317";

// ---------------------------------------------------------------------------
// Byte encoding helpers
// ---------------------------------------------------------------------------

/** Create a Uint8Array of `len` bytes all set to `fill`. */
export function repeatByte(fill: number, len: number): Uint8Array {
  return new Uint8Array(len).fill(fill);
}

/** Encode a Uint8Array to standard base64 (Go's encoding/json default). */
export function toBase64(bytes: Uint8Array): string {
  // Node 18+ Buffer is available
  return Buffer.from(bytes).toString("base64");
}

/** Decode a hex string to Uint8Array. */
export function fromHex(hex: string): Uint8Array {
  return Buffer.from(hex, "hex");
}

/** Encode a Uint8Array to hex string. */
export function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

// ---------------------------------------------------------------------------
// Proof fixture loading
// ---------------------------------------------------------------------------

const FIXTURES_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "fixtures",
);

// ---------------------------------------------------------------------------
// Vote commitment tree CLI (Rust shell-out)
// ---------------------------------------------------------------------------

/** Path to the vote-commitment-tree-client Cargo.toml (for `cargo run --manifest-path`). */
const TREE_CLI_MANIFEST = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..", "..", "..", "..",
  "vote-commitment-tree-client",
  "Cargo.toml",
);

/**
 * Run the `vote-tree-cli` Rust binary with the given arguments and return stdout.
 *
 * Uses `cargo run --manifest-path` so no `cd` is needed. The 120s timeout
 * accommodates first-time compilation. On failure (non-zero exit), `execFileSync`
 * throws — the test naturally fails with the CLI's stderr message.
 */
export function runTreeCli(args: string[]): string {
  return execFileSync("cargo", [
    "run", "--quiet",
    "--manifest-path", TREE_CLI_MANIFEST,
    "--bin", "vote-tree-cli",
    "--", ...args,
  ], { encoding: "utf-8", timeout: 120_000 }).trim();
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

/** Read a binary fixture file from tests/api/fixtures/. */
export function loadFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(FIXTURES_DIR, name)));
}

/** Read a JSON fixture file from tests/api/fixtures/. */
export function loadJsonFixture<T = unknown>(name: string): T {
  const raw = readFileSync(path.join(FIXTURES_DIR, name), "utf-8");
  return JSON.parse(raw) as T;
}

// ---------------------------------------------------------------------------
// ElGamal tally fixtures (generated by Go: TestGenerateElGamalFixtures)
// ---------------------------------------------------------------------------

/** Shape of the elgamal_tally.json fixture. */
export interface ElGamalTallyFixtures {
  /** EA public key, base64-encoded 32 bytes (compressed Pallas point). */
  ea_pk: string;
  /** Encrypted vote shares, each base64-encoded 64-byte ciphertext. */
  shares: Array<{ value: number; enc_share: string }>;
  /** HomomorphicAdd of all shares, base64-encoded 64 bytes. */
  expected_accumulated: string;
  /** Sum of all share values. */
  expected_total: number;
}

let _elgamalFixtures: ElGamalTallyFixtures | null = null;

/**
 * Load the Go-generated ElGamal tally fixtures.
 *
 * Returns the fixture data if the file exists, or null if it hasn't been
 * generated yet (run: `go test -run TestGenerateElGamalFixtures ./crypto/elgamal/`).
 */
export function getElGamalFixtures(): ElGamalTallyFixtures | null {
  if (_elgamalFixtures) return _elgamalFixtures;
  try {
    _elgamalFixtures = loadJsonFixture<ElGamalTallyFixtures>("elgamal_tally.json");
    return _elgamalFixtures;
  } catch {
    console.warn(
      "[zally-api-tests] elgamal_tally.json not found in tests/api/fixtures/. " +
        "Run `go test -run TestGenerateElGamalFixtures ./crypto/elgamal/` to generate.",
    );
    return null;
  }
}

// Lazy-loaded real Halo2 proof + public input (toy circuit: 7 * a^2 * b^2 = c).
let _realProof: Uint8Array | null = null;
let _realInput: Uint8Array | null = null;
let _fixturesAvailable: boolean | null = null;

/**
 * Load the real Halo2 toy proof fixtures from disk.
 * Returns { proof, publicInput } if the fixture files exist, or null if they
 * are missing (e.g. `make fixtures` has not been run).
 *
 * The publicInput is the 32-byte LE Pallas Fp encoding of c=252 (a=2, b=3).
 * It is used as the `gov_comm` field in MsgDelegateVote, since the toy
 * circuit's VerifyDelegation uses inputs.GovComm as the public input (keeping
 * rk free for RedPallas signature verification).
 */
export function getRealProofFixtures(): {
  proof: Uint8Array;
  publicInput: Uint8Array;
} | null {
  if (_fixturesAvailable === false) return null;
  if (_realProof && _realInput) {
    return { proof: _realProof, publicInput: _realInput };
  }
  try {
    _realProof = loadFixture("toy_valid_proof.bin");
    _realInput = loadFixture("toy_valid_input.bin");
    _fixturesAvailable = true;
    return { proof: _realProof, publicInput: _realInput };
  } catch {
    _fixturesAvailable = false;
    console.warn(
      "[zally-api-tests] Halo2 fixture files not found in tests/api/fixtures/. " +
        "Falling back to mock proof data. Run `make fixtures-ts` to generate real fixtures.",
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Real delegation proof fixture (ZKP #1)
// ---------------------------------------------------------------------------

/** Full delegation proof fixture with all fields needed for e2e test. */
export interface DelegationFixture {
  proof: Uint8Array;
  rk: Uint8Array;
  spend_auth_sig: Uint8Array;
  sighash: Uint8Array;
  signed_note_nullifier: Uint8Array;
  cmx_new: Uint8Array;
  enc_memo: Uint8Array;
  gov_comm: Uint8Array;
  gov_nullifiers: Uint8Array[];
  vote_round_id: Uint8Array;
  session: {
    snapshot_height: number;
    snapshot_blockhash: Uint8Array;
    proposals_hash: Uint8Array;
    vote_end_time: number;
    nullifier_imt_root: Uint8Array;
    nc_root: Uint8Array;
  };
}

let _delegationFixture: DelegationFixture | null = null;
let _delegationFixtureAvailable: boolean | null = null;

/**
 * Load the real delegation proof fixture (delegation_real.json).
 * Returns the full fixture if it exists, or null if missing.
 *
 * All byte fields in the JSON are base64-encoded; this function decodes them.
 */
export function getRealDelegationFixture(): DelegationFixture | null {
  if (_delegationFixtureAvailable === false) return null;
  if (_delegationFixture) return _delegationFixture;

  try {
    const raw = readFileSync(
      path.join(FIXTURES_DIR, "delegation_real.json"),
      "utf-8",
    );
    const json = JSON.parse(raw);

    const fromB64 = (s: string): Uint8Array => Buffer.from(s, "base64");

    _delegationFixture = {
      proof: fromB64(json.proof),
      rk: fromB64(json.rk),
      spend_auth_sig: fromB64(json.spend_auth_sig),
      sighash: fromB64(json.sighash),
      signed_note_nullifier: fromB64(json.signed_note_nullifier),
      cmx_new: fromB64(json.cmx_new),
      enc_memo: fromB64(json.enc_memo),
      gov_comm: fromB64(json.gov_comm),
      gov_nullifiers: (json.gov_nullifiers as string[]).map(fromB64),
      vote_round_id: fromB64(json.vote_round_id),
      session: {
        snapshot_height: json.session.snapshot_height,
        snapshot_blockhash: fromB64(json.session.snapshot_blockhash),
        proposals_hash: fromB64(json.session.proposals_hash),
        vote_end_time: json.session.vote_end_time,
        nullifier_imt_root: fromB64(json.session.nullifier_imt_root),
        nc_root: fromB64(json.session.nc_root),
      },
    };
    _delegationFixtureAvailable = true;
    return _delegationFixture;
  } catch {
    _delegationFixtureAvailable = false;
    console.warn(
      "[zally-api-tests] delegation_real.json not found in tests/api/fixtures/. " +
        "Falling back to toy proof + mock data. " +
        "Run `make fixtures` to generate real delegation fixtures.",
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Round ID derivation (mirrors deriveRoundID in keeper/msg_server.go)
// ---------------------------------------------------------------------------

/** Write a uint64 as 8 bytes big-endian into a Uint8Array. */
function uint64BE(value: number): Uint8Array {
  const buf = new Uint8Array(8);
  const view = new DataView(buf.buffer);
  // DataView setBigUint64 handles full 64-bit range
  view.setBigUint64(0, BigInt(value), false); // big-endian
  return buf;
}

export interface SetupRoundFields {
  snapshot_height: number;
  snapshot_blockhash: Uint8Array;
  proposals_hash: Uint8Array;
  vote_end_time: number;
  nullifier_imt_root: Uint8Array;
  nc_root: Uint8Array;
}

/**
 * Derive the vote_round_id exactly as the chain does:
 *   Blake2b-256(snapshot_height || snapshot_blockhash || proposals_hash ||
 *               vote_end_time || nullifier_imt_root || nc_root)
 */
export function deriveRoundId(fields: SetupRoundFields): Uint8Array {
  const parts: Uint8Array[] = [
    uint64BE(fields.snapshot_height),
    fields.snapshot_blockhash,
    fields.proposals_hash,
    uint64BE(fields.vote_end_time),
    fields.nullifier_imt_root,
    fields.nc_root,
  ];
  const total = parts.reduce((s, p) => s + p.length, 0);
  const data = new Uint8Array(total);
  let offset = 0;
  for (const p of parts) {
    data.set(p, offset);
    offset += p.length;
  }
  return blake2b(data, { dkLen: 32 });
}

// ---------------------------------------------------------------------------
// Payload builders
// ---------------------------------------------------------------------------

// Auto-incrementing counter seeded from timestamp to ensure uniqueness
// across test runs (chain state persists).
let roundCounter = Math.floor(Date.now() / 1000) % 1_000_000;

/**
 * A single tally entry for MsgSubmitTally.
 */
export interface TallyEntryPayload {
  proposal_id: number;
  vote_decision: number;
  total_value: number;
  decryption_proof?: string; // base64, optional for now
}

/**
 * Build a valid MsgSubmitTally JSON body.
 *
 * @param roundId - The vote_round_id (raw bytes) to target.
 * @param creator - The session creator (must match the original creator).
 * @param entries - Tally entries with decrypted totals per (proposal, decision).
 */
export function makeSubmitTallyPayload(
  roundId: Uint8Array,
  creator = "zvote1admin",
  entries: TallyEntryPayload[] = [],
) {
  return {
    vote_round_id: toBase64(roundId),
    creator,
    entries,
  };
}

/**
 * Build a valid MsgCreateVotingSession JSON body.
 * Returns both the JSON-ready object (with base64 byte fields) and the raw
 * fields needed for deriveRoundId.
 *
 * Each call produces a unique round ID by incrementing snapshot_height,
 * unless `opts.sessionOverride` is provided (e.g. from a delegation fixture).
 *
 * @param eaPkBytes - EA public key (32-byte compressed Pallas point). Use
 *   getElGamalFixtures().ea_pk decoded from base64, or any valid 32-byte key.
 * @param opts.expiresInSec - Override vote_end_time offset (default: 3600 = 1 hour).
 * @param opts.sessionOverride - Use exact session params (from delegation fixture).
 */
export function makeCreateVotingSessionPayload(
  eaPkBytes: Uint8Array,
  opts?: {
    expiresInSec?: number;
    sessionOverride?: SetupRoundFields;
  },
) {
  let fields: SetupRoundFields;

  if (opts?.sessionOverride) {
    fields = opts.sessionOverride;
  } else {
    const snapshotBlockhash = repeatByte(0xaa, 32);
    const proposalsHash = repeatByte(0xbb, 32);
    const nullifierImtRoot = repeatByte(0xcc, 32);
    const ncRoot = repeatByte(0xdd, 32);
    const snapshotHeight = 1000 + roundCounter++;
    const voteEndTime =
      Math.floor(Date.now() / 1000) + (opts?.expiresInSec ?? 3600);

    fields = {
      snapshot_height: snapshotHeight,
      snapshot_blockhash: snapshotBlockhash,
      proposals_hash: proposalsHash,
      vote_end_time: voteEndTime,
      nullifier_imt_root: nullifierImtRoot,
      nc_root: ncRoot,
    };
  }

  const vkZkp1 = repeatByte(0xf1, 64);
  const vkZkp2 = repeatByte(0xf2, 64);
  const vkZkp3 = repeatByte(0xf3, 64);

  const body = {
    creator: "zvote1admin",
    snapshot_height: fields.snapshot_height,
    snapshot_blockhash: toBase64(fields.snapshot_blockhash),
    proposals_hash: toBase64(fields.proposals_hash),
    vote_end_time: fields.vote_end_time,
    nullifier_imt_root: toBase64(fields.nullifier_imt_root),
    nc_root: toBase64(fields.nc_root),
    ea_pk: toBase64(eaPkBytes),
    vk_zkp1: toBase64(vkZkp1),
    vk_zkp2: toBase64(vkZkp2),
    vk_zkp3: toBase64(vkZkp3),
    proposals: [
      { id: 0, title: "Proposal A", description: "First proposal" },
      { id: 1, title: "Proposal B", description: "Second proposal" },
    ],
  };

  return { body, fields, roundId: deriveRoundId(fields) };
}

// ---------------------------------------------------------------------------
// RedPallas signature fixtures (pre-computed, real cryptographic values)
// ---------------------------------------------------------------------------

// These are generated by `make fixtures` from circuits/tests/generate_fixtures.rs.
// The signature covers sighash = Blake2b-256("ZALLY_SIGHASH_V0").
// The sighash is now sent as a field on MsgDelegateVote (msg.sighash).

/** Real RedPallas verification key (rk), 32 bytes, base64-encoded. */
export const REAL_RK = "ALaMc32ZWh3P95+tdny+DW0VBa4LSeRDRjyztAv4lzo=";

/** Real RedPallas signature over REAL_SIGHASH, 64 bytes, base64-encoded. */
export const REAL_SIG =
  "1M/j74DlrJzJquyIVF5Z9ipi4MsRu8yRJAcsizi14xHGGb7qc40vWeKtmE2+/HrzMQTHfc3qQoC71SKsm67gBw==";

/** The sighash that REAL_SIG was generated over: Blake2b-256("ZALLY_SIGHASH_V0"). */
export const REAL_SIGHASH = blake2b(
  new TextEncoder().encode("ZALLY_SIGHASH_V0"),
  { dkLen: 32 },
);

// Auto-incrementing nullifier counter to avoid collisions with spent nullifiers
// from previous test runs (chain state persists).
let nullifierCounter = Math.floor(Date.now() / 1000) % 1_000_000;

/** Create a unique 32-byte value by writing a counter value into it.
 *
 * The result is a valid canonical Pallas base field element (LE value < p).
 * This is required because some callers use these values as commitment tree
 * leaves, which the Poseidon Merkle root FFI deserializes via Fp::from_repr.
 * The Pallas modulus has MSB ≈ 0x40, so byte 31 (MSB in LE) must be < 0x40
 * to guarantee the encoding is canonical.
 */
function makeUniqueNullifier(): Uint8Array {
  const nf = new Uint8Array(32);
  const view = new DataView(nf.buffer);
  view.setUint32(0, nullifierCounter++, false);
  // Fill bytes 4–30 with a non-zero pattern.
  for (let i = 4; i < 31; i++) nf[i] = 0xab;
  // Byte 31 is the MSB in little-endian Pallas Fp encoding.
  // Must be < 0x40 to stay below the field modulus.
  nf[31] = 0x0a;
  return nf;
}

/**
 * Build a valid MsgDelegateVote JSON body.
 *
 * By default, uses the toy circuit proof with standalone RedPallas
 * fixtures (or mock data). Each call produces unique nullifiers.
 *
 * When `opts.useRealFixture` is true AND delegation_real.json exists,
 * uses the full ZKP #1 delegation proof with all 12 matching public
 * inputs and a RedPallas signature generated with the same rk. The
 * fixture's vote_round_id must match the session's derived round ID
 * (the caller is responsible for creating the session with matching
 * params — see `makeCreateVotingSessionPayload` with `sessionOverride`).
 *
 * @param roundId - The vote_round_id (raw bytes) to target.
 * @param opts.useRealFixture - When true, use the real delegation fixture.
 */
export function makeDelegateVotePayload(
  roundId: Uint8Array,
  opts?: { useRealFixture?: boolean },
) {
  // Use real delegation fixture only when explicitly requested.
  if (opts?.useRealFixture) {
    const delegationFixture = getRealDelegationFixture();
    if (delegationFixture) {
      return {
        rk: toBase64(delegationFixture.rk),
        spend_auth_sig: toBase64(delegationFixture.spend_auth_sig),
        sighash: toBase64(delegationFixture.sighash),
        signed_note_nullifier: toBase64(delegationFixture.signed_note_nullifier),
        cmx_new: toBase64(delegationFixture.cmx_new),
        enc_memo: toBase64(delegationFixture.enc_memo),
        gov_comm: toBase64(delegationFixture.gov_comm),
        gov_nullifiers: delegationFixture.gov_nullifiers.map(toBase64),
        proof: toBase64(delegationFixture.proof),
        vote_round_id: toBase64(roundId),
      };
    }
  }

  // Default: toy circuit proof + standalone RedPallas signature.
  const nf1 = makeUniqueNullifier();
  const nf2 = makeUniqueNullifier();
  const cmx = makeUniqueNullifier(); // unique cmx_new

  const toyFixtures = getRealProofFixtures();
  const proof = toyFixtures
    ? toyFixtures.proof
    : Buffer.from("mock-delegation-proof");
  const govComm = toyFixtures
    ? toyFixtures.publicInput
    : makeUniqueNullifier();

  return {
    rk: REAL_RK,
    spend_auth_sig: REAL_SIG,
    sighash: toBase64(REAL_SIGHASH),
    signed_note_nullifier: toBase64(repeatByte(0x03, 32)),
    cmx_new: toBase64(cmx),
    enc_memo: toBase64(repeatByte(0x05, 64)),
    gov_comm: toBase64(govComm),
    gov_nullifiers: [toBase64(nf1), toBase64(nf2)],
    proof: toBase64(proof),
    vote_round_id: toBase64(roundId),
  };
}

/**
 * Build a valid MsgCastVote JSON body with mock proof bytes.
 *
 * The chain's MockVerifier accepts any proof bytes for ZKP #2 in dev mode.
 * Each call produces unique nullifiers to avoid collisions.
 *
 * @param roundId - The vote_round_id (raw bytes) to target.
 * @param anchorHeight - The commitment tree anchor height (from GET /commitment-tree/latest).
 */
export function makeCastVotePayload(roundId: Uint8Array, anchorHeight: number) {
  return {
    van_nullifier: toBase64(makeUniqueNullifier()),
    vote_authority_note_new: toBase64(makeUniqueNullifier()),
    vote_commitment: toBase64(makeUniqueNullifier()),
    proposal_id: 0,
    proof: toBase64(Buffer.from("mock-cast-vote-proof")),
    vote_round_id: toBase64(roundId),
    vote_comm_tree_anchor_height: anchorHeight,
  };
}

/**
 * Build a valid MsgRevealShare JSON body with mock proof bytes.
 *
 * The chain's MockVerifier accepts any proof bytes for ZKP #3 in dev mode.
 * Each call produces unique nullifiers to avoid collisions.
 *
 * enc_share is a 64-byte ElGamal ciphertext (base64-encoded). Pass a
 * pre-built ciphertext via opts.encShare (e.g. loaded from Go fixtures),
 * or omit to use a default 64-byte 0x88 stub.
 *
 * @param roundId - The vote_round_id (raw bytes) to target.
 * @param anchorHeight - The commitment tree anchor height (from GET /commitment-tree/latest).
 * @param opts - Optional overrides for enc_share, proposal_id, vote_decision.
 */
export function makeRevealSharePayload(
  roundId: Uint8Array,
  anchorHeight: number,
  opts?: { encShare?: string; proposalId?: number; voteDecision?: number },
) {
  // Default enc_share: 64 bytes of 0x88 (a stub ciphertext).
  const defaultEncShare = toBase64(repeatByte(0x88, 64));
  return {
    share_nullifier: toBase64(makeUniqueNullifier()),
    enc_share: opts?.encShare ?? defaultEncShare,
    proposal_id: opts?.proposalId ?? 0,
    vote_decision: opts?.voteDecision ?? 1,
    proof: toBase64(Buffer.from("mock-reveal-share-proof")),
    vote_round_id: toBase64(roundId),
    vote_comm_tree_anchor_height: anchorHeight,
  };
}

// ---------------------------------------------------------------------------
// HTTP helpers
// ---------------------------------------------------------------------------

/**
 * Returns true if the error is a retryable socket error (e.g. stale keep-alive
 * connection closed by the server). Node.js's built-in fetch (undici) does NOT
 * automatically retry POST requests on dead sockets, so we handle it here.
 */
function isRetryableSocketError(err: unknown): boolean {
  if (!(err instanceof TypeError)) return false;
  const cause = (err as { cause?: { code?: string } }).cause;
  if (!cause?.code) return false;
  return (
    cause.code === "UND_ERR_SOCKET" ||
    cause.code === "ECONNRESET" ||
    cause.code === "ECONNREFUSED"
  );
}

/**
 * fetch wrapper that retries on transient socket errors (stale keep-alive
 * connections, brief server unavailability). Only retries on network-level
 * errors — HTTP 4xx/5xx responses are returned normally, not retried.
 *
 * Note: 502 from delegation broadcasts (slow Halo2 CheckTx) should NOT be
 * retried here — the tx is typically already in the mempool, so retrying
 * produces "tx already exists" errors. Handle 502 at the test level instead.
 */
async function fetchWithRetry(
  url: string,
  init: RequestInit,
  maxRetries = 2,
): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    try {
      return await fetch(url, init);
    } catch (err) {
      if (attempt >= maxRetries || !isRetryableSocketError(err)) throw err;
      // Brief back-off before retry (500ms, 1000ms).
      await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
    }
  }
}

/** POST JSON to a /zally/v1/* endpoint and return the parsed response. */
export async function postJSON(path: string, body: unknown) {
  const res = await fetchWithRetry(`${BASE_URL}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  return { status: res.status, json };
}

/** GET a /zally/v1/* endpoint and return the parsed response. */
export async function getJSON(path: string) {
  const res = await fetchWithRetry(`${BASE_URL}${path}`, {});
  const json = await res.json();
  return { status: res.status, json };
}

// ---------------------------------------------------------------------------
// Wait helper -- give CometBFT time to include the tx in a block
// ---------------------------------------------------------------------------

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Default block time wait (slightly over one block period). */
export const BLOCK_WAIT_MS = 6000;
