/**
 * End-to-end integration test for the full voting flow.
 *
 * Exercises the complete lifecycle:
 *   1. MsgCreateVotingSession — create a round
 *   2. MsgDelegateVote        — real ZKP #1 delegation proof + RedPallas sig
 *   3. MsgCastVote            — cast vote with mock proof (ZKP #2)
 *   4. MsgRevealShare         — reveal share with mock proof (ZKP #3)
 *   5. Query tally            — verify accumulated vote
 *   6. MsgSubmitTally         — finalize the session (TALLYING → FINALIZED)
 *
 * ZKP #1 (delegation): uses the real delegation fixture (delegation_real.json)
 * when available, so the test works with both MockVerifier and real Halo2
 * verification (make install-ffi). Falls back to toy proof otherwise.
 * ZKP #2, #3: toy/mock proofs — MockVerifier accepts any bytes.
 *
 * Prerequisites:
 *   1. Build chain: make install (or make install-ffi for real ZKP #1 verification)
 *   2. Start chain: make init && make start
 *   3. Generate fixtures: make fixtures (for ElGamal + delegation + RedPallas fixtures)
 */

import { describe, it, expect, beforeAll } from "vitest";
import {
  makeCreateVotingSessionPayload,
  makeDelegateVotePayload,
  makeCastVotePayload,
  makeRevealSharePayload,
  makeSubmitTallyPayload,
  getRealDelegationFixture,
  postJSON,
  getJSON,
  sleep,
  BLOCK_WAIT_MS,
  toHex,
  getElGamalFixtures,
  runTreeCli,
  BASE_URL,
  type TallyEntryPayload,
} from "./helpers.js";

// ---------------------------------------------------------------------------
// Helper: poll until a round reaches the expected status (integer enum value).
// ---------------------------------------------------------------------------

/** SessionStatus enum values (protobuf int32 serialized by encoding/json). */
const SESSION_STATUS = {
  UNSPECIFIED: 0,
  ACTIVE: 1,
  TALLYING: 2,
  FINALIZED: 3,
} as const;

/**
 * Poll GET /zally/v1/round/{roundIdHex} until the round reaches `expected`
 * status, or throw after `timeoutMs`.
 */
async function waitForRoundStatus(
  roundIdHex: string,
  expected: number,
  timeoutMs = 90_000,
  intervalMs = 3_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const { json } = await getJSON(`/zally/v1/round/${roundIdHex}`);
    if (json.round?.status === expected) return;
    await sleep(intervalMs);
  }
  throw new Error(
    `Timed out waiting for round ${roundIdHex} to reach status ${expected}`,
  );
}

// ---------------------------------------------------------------------------
// Load ElGamal fixtures once (deterministic — generated by Go).
// ---------------------------------------------------------------------------

const fixtures = getElGamalFixtures();
if (!fixtures) {
  throw new Error(
    "ElGamal fixtures not found. Run: go test -run TestGenerateElGamalFixtures ./crypto/elgamal/",
  );
}
const FIXTURE_EA_PK = new Uint8Array(Buffer.from(fixtures.ea_pk, "base64"));

// ===========================================================================
// E2E Voting Flow — full lifecycle through FINALIZED
//
// The delegation fixture (delegation_real.json) has a short vote_end_time
// (~3 minutes from fixture generation). Run `make fixtures && make test-api`
// in quick succession so the session expires within the test timeout.
// ===========================================================================

describe("E2E Voting Flow", () => {
  const SESSION_CREATOR = "zvote1admin";

  // Shared state across sequential test steps.
  let roundId: Uint8Array;
  let roundIdHex: string;
  let anchorHeight: number;

  // -------------------------------------------------------------------------
  // Step 1: Create voting session
  // -------------------------------------------------------------------------

  beforeAll(async () => {
    // When the real delegation fixture is available, use its session params
    // so the vote_round_id derived from the session matches the one baked
    // into the delegation proof. This is required when the chain is built
    // with real Halo2 verification (make install-ffi).
    const delegFixture = getRealDelegationFixture();
    const sessionOpts = delegFixture
      ? { sessionOverride: delegFixture.session }
      : undefined;

    // Safeguard: verify the fixture's vote_end_time hasn't already passed.
    // If it has, the EndBlocker will immediately transition the round to
    // TALLYING and delegation will fail. Regenerate with: make fixtures
    if (delegFixture) {
      const now = Math.floor(Date.now() / 1000);
      const remaining = delegFixture.session.vote_end_time - now;
      if (remaining < 60) {
        throw new Error(
          `Delegation fixture is stale: vote_end_time expires in ${remaining}s. ` +
          `Regenerate with: make fixtures && make test-api`,
        );
      }
      console.log(`[E2E] fixture vote_end_time expires in ${remaining}s`);
    }

    const { body, roundId: rid } = makeCreateVotingSessionPayload(
      FIXTURE_EA_PK,
      sessionOpts,
    );
    roundId = rid;
    roundIdHex = toHex(roundId);

    const res = await postJSON("/zally/v1/create-voting-session", body);
    expect(res.json.code, `create session rejected: ${res.json.log}`).toBe(0);

    // Wait for the session creation tx to be included in a block.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 1: Delegate vote (ZKP #1 — real delegation fixture when available)
  // -------------------------------------------------------------------------

  it("step 1: delegate vote succeeds", async () => {
    const delegationBody = makeDelegateVotePayload(roundId, { useRealFixture: true });
    const { status, json } = await postJSON(
      "/zally/v1/delegate-vote",
      delegationBody,
    );

    expect(
      status,
      `delegation HTTP ${status}: ${JSON.stringify(json)}`,
    ).toBe(200);
    expect(json.code, `delegation rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for delegation tx to be included — EndBlocker computes tree root.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 2: Query commitment tree for anchor height (derisk: root, next_index)
  // -------------------------------------------------------------------------

  it("step 2: commitment tree has a computed root after delegation", async () => {
    // The EndBlocker computes the tree root at the end of the block that
    // includes the delegation tx. Poll until the tree has leaves (the query
    // may arrive before the EndBlocker has run).
    let treeJson: any;
    for (let attempt = 0; attempt < 10; attempt++) {
      const { status, json } = await getJSON("/zally/v1/commitment-tree/latest");
      expect(status).toBe(200);
      if (json.tree && json.tree.height > 0) {
        treeJson = json;
        break;
      }
      await sleep(2000);
    }
    expect(treeJson, "tree never populated after delegation").toBeTruthy();

    expect(treeJson.tree.height).toBeGreaterThan(0);
    // DelegateVote appends 2 leaves: cmx_new, gov_comm. Use ≥ 2 in case
    // the chain has leftover state from a prior test run.
    expect(treeJson.tree.next_index).toBeGreaterThanOrEqual(2);
    // Root is computed by EndBlocker (Poseidon or placeholder); must be present and 32 bytes.
    expect(treeJson.tree.root).toBeTruthy();
    const rootBytes = Buffer.from(treeJson.tree.root, "base64");
    expect(rootBytes.length).toBe(32);

    // Save anchor height for CastVote and RevealShare.
    anchorHeight = treeJson.tree.height;
  }, 30_000);

  it("step 2b: commitment tree at anchor height returns same root and next_index", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/commitment-tree/${anchorHeight}`,
    );

    expect(status).toBe(200);
    expect(json.tree).toBeTruthy();
    expect(json.tree.height).toBe(anchorHeight);
    expect(json.tree.next_index).toBeGreaterThanOrEqual(2);
    expect(json.tree.root).toBeTruthy();
    expect(Buffer.from(json.tree.root, "base64").length).toBe(32);
  });

  // -------------------------------------------------------------------------
  // Step 2c: Rust TreeClient sync — independently reconstructs the same root
  // -------------------------------------------------------------------------

  it("step 2c: Rust tree client sync matches chain root (2 leaves)", () => {
    const output = runTreeCli(["sync", "--node", BASE_URL]);

    expect(output).toContain("leaves synced:     2");
    expect(output).toContain("root match:");
    expect(output).toContain("OK");
  }, 120_000); // generous timeout for first cargo build

  // -------------------------------------------------------------------------
  // Step 2d: Witness generation for first VAN leaf (position 0)
  // -------------------------------------------------------------------------

  it("step 2d: witness for first VAN leaf (position 0) verifies", () => {
    const output = runTreeCli([
      "witness", "--node", BASE_URL, "--position", "0",
    ]);

    expect(output).toContain("Witness (hex):");
    expect(output).toContain("Witness size:  772 bytes");
    expect(output).toContain("Anchor root:");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 4: Cast vote (ZKP #2 — mock proof)
  // -------------------------------------------------------------------------

  it("step 3: cast vote succeeds with mock proof", async () => {
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const { status, json } = await postJSON(
      "/zally/v1/cast-vote",
      castBody,
    );

    expect(status).toBe(200);
    expect(json.code, `cast vote rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for cast-vote tx to be included — EndBlocker updates tree root.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 5: Query updated commitment tree for reveal anchor (derisk: next_index, root)
  // -------------------------------------------------------------------------

  it("step 4: commitment tree updated after cast vote", async () => {
    const { status, json } = await getJSON(
      "/zally/v1/commitment-tree/latest",
    );

    expect(status).toBe(200);
    expect(json.tree).toBeTruthy();
    expect(json.tree.height).toBeGreaterThanOrEqual(anchorHeight);
    // CastVote appends 2 leaves: vote_authority_note_new, vote_commitment. Total 4.
    expect(json.tree.next_index).toBe(4);
    expect(json.tree.root).toBeTruthy();
    expect(Buffer.from(json.tree.root, "base64").length).toBe(32);

    // Update anchor height for RevealShare.
    anchorHeight = json.tree.height;
  });

  it("step 4b: commitment leaves API returns blocks with correct leaf counts", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/commitment-tree/leaves?from_height=1&to_height=${anchorHeight}`,
    );

    expect(status).toBe(200);
    expect(json.blocks).toBeDefined();
    expect(Array.isArray(json.blocks)).toBe(true);
    // Delegate block: 2 leaves; cast block: 2 leaves.
    const totalLeaves = json.blocks.reduce(
      (sum: number, b: { leaves?: unknown[] }) => sum + (b.leaves?.length ?? 0),
      0,
    );
    expect(totalLeaves).toBe(4);
    // Each block has height, start_index, leaves; each leaf is 32 bytes (base64).
    // start_index may be omitted when 0 (proto3 omitempty).
    let expectedStart = 0;
    for (const block of json.blocks) {
      expect(block.height).toBeGreaterThan(0);
      expect(block.start_index ?? 0).toBe(expectedStart);
      expect(block.leaves).toBeDefined();
      expect(Array.isArray(block.leaves)).toBe(true);
      for (const leaf of block.leaves) {
        expect(Buffer.from(leaf, "base64").length).toBe(32);
      }
      expectedStart += block.leaves.length;
    }
  });

  // -------------------------------------------------------------------------
  // Step 4c: Rust TreeClient sync — root still matches after cast-vote growth
  // -------------------------------------------------------------------------

  it("step 4c: Rust tree client sync matches chain root (4 leaves)", () => {
    const output = runTreeCli(["sync", "--node", BASE_URL]);

    expect(output).toContain("leaves synced:     4");
    expect(output).toContain("root match:");
    expect(output).toContain("OK");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 4d: Witness for VAN at position 2 (appended by CastVote)
  // -------------------------------------------------------------------------

  it("step 4d: witness for cast-vote VAN leaf (position 2) verifies", () => {
    const output = runTreeCli([
      "witness", "--node", BASE_URL, "--position", "2",
    ]);

    expect(output).toContain("Witness (hex):");
    expect(output).toContain("Witness size:  772 bytes");
    expect(output).toContain("Anchor root:");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 6: Reveal share (ZKP #3 — mock proof)
  // -------------------------------------------------------------------------

  it("step 5: reveal share succeeds with mock proof", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
      encShare: fixtures!.shares[0].enc_share,
    });
    const { status, json } = await postJSON(
      "/zally/v1/reveal-share",
      revealBody,
    );

    expect(status).toBe(200);
    expect(json.code, `reveal share rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for reveal tx to be included.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 7: Query tally and verify accumulated vote
  // -------------------------------------------------------------------------

  it("step 6: tally reflects the revealed vote as encrypted ciphertext", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/tally/${roundIdHex}/0`,
    );

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Decision 1 should have an accumulated ciphertext (base64 string, 64 bytes).
    expect(json.tally["1"]).toBeTruthy();
    expect(typeof json.tally["1"]).toBe("string"); // base64-encoded bytes
  });

  // -------------------------------------------------------------------------
  // Negative paths: duplicate nullifier rejection
  // -------------------------------------------------------------------------

  it("step 7: duplicate cast-vote nullifier is rejected", async () => {
    // Build a cast-vote payload with the same structure — but the chain
    // already recorded the previous van_nullifier. We need to reuse the
    // exact same nullifier to trigger rejection, so we build manually.
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const res1 = await postJSON("/zally/v1/cast-vote", castBody);
    expect(res1.json.code, `first cast should succeed: ${res1.json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);

    // Resubmit with the SAME van_nullifier — should be rejected.
    const duplicate = { ...makeCastVotePayload(roundId, anchorHeight) };
    duplicate.van_nullifier = castBody.van_nullifier;

    const res2 = await postJSON("/zally/v1/cast-vote", duplicate);
    expect(res2.status).toBe(200);
    expect(res2.json.code).not.toBe(0);
    expect(res2.json.log).toMatch(/nullifier/i);
  });

  it("step 8: duplicate reveal-share nullifier is rejected", async () => {
    // Use voteDecision: 2 so the stub enc_share doesn't pollute the
    // tally["1"] bucket that step 11 checks against expected_accumulated.
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 2,
    });
    const res1 = await postJSON("/zally/v1/reveal-share", revealBody);
    expect(res1.json.code, `first reveal should succeed: ${res1.json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);

    // Resubmit with the SAME share_nullifier — should be rejected.
    const duplicate = { ...makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 2,
    }) };
    duplicate.share_nullifier = revealBody.share_nullifier;

    const res2 = await postJSON("/zally/v1/reveal-share", duplicate);
    // The chain rejects the duplicate nullifier. Depending on how the error
    // surfaces through BroadcastTxSync, the API may return either:
    //   a) HTTP 200 with json.code != 0  (ante rejection in CheckTx response)
    //   b) HTTP 502 with an error body   (broadcast-level error)
    const rejected =
      res2.status !== 200 || (res2.json.code !== undefined && res2.json.code !== 0);
    expect(rejected, `expected rejection but got status=${res2.status} code=${res2.json.code}`).toBe(true);
  });

  // =========================================================================
  // Tallying & finalization (same round — expires naturally)
  //
  // The delegation fixture uses a short vote_end_time (~3 min from fixture
  // generation). After the ACTIVE-phase tests above, we wait for the
  // EndBlocker to transition the round ACTIVE → TALLYING, then continue.
  // =========================================================================

  it("step 9: wait for TALLYING transition", async () => {
    // The fixture's vote_end_time is ~5 minutes from fixture generation.
    // Depending on how long ago fixtures were generated, we may need to
    // wait up to several minutes for the EndBlocker to transition the round.
    const delegFixture = getRealDelegationFixture();
    const now = Math.floor(Date.now() / 1000);
    const secsUntilExpiry = delegFixture
      ? delegFixture.session.vote_end_time - now
      : 0;
    // Wait at most secsUntilExpiry + 30s buffer (minimum 60s).
    const waitMs = Math.max(60_000, (secsUntilExpiry + 30) * 1000);
    console.log(`[E2E] waiting up to ${Math.round(waitMs / 1000)}s for TALLYING (vote_end_time in ${secsUntilExpiry}s)`);

    await waitForRoundStatus(roundIdHex, SESSION_STATUS.TALLYING, waitMs);

    const { status, json } = await getJSON(`/zally/v1/round/${roundIdHex}`);
    expect(status).toBe(200);
    expect(json.round).toBeTruthy();
    expect(json.round.status).toBe(SESSION_STATUS.TALLYING);
  }, 600_000); // generous timeout — may need to wait for vote_end_time

  it("step 10: reveal share succeeds during TALLYING", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
      encShare: fixtures!.shares[1].enc_share,
    });
    const { status, json } = await postJSON("/zally/v1/reveal-share", revealBody);

    expect(status).toBe(200);
    expect(json.code, `reveal during TALLYING rejected: ${json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);
  });

  it("step 11: accumulated tally matches Go-computed HomomorphicAdd", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally/${roundIdHex}/0`);

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Decision 1 should have an accumulated ciphertext (from two reveals).
    expect(json.tally["1"]).toBeTruthy();
    expect(typeof json.tally["1"]).toBe("string"); // base64-encoded ciphertext

    // The on-chain HomomorphicAdd(share[0], share[1]) should produce the
    // exact same ciphertext bytes as the Go-computed expected_accumulated.
    expect(json.tally["1"]).toBe(fixtures!.expected_accumulated);
  });

  it("step 12: delegate vote rejected during TALLYING", async () => {
    const delegationBody = makeDelegateVotePayload(roundId);
    const { status, json } = await postJSON("/zally/v1/delegate-vote", delegationBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    // The ante handler rejects non-ACTIVE messages for delegation.
    expect(json.log).toBeTruthy();
  });

  it("step 13: cast vote rejected during TALLYING", async () => {
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const { status, json } = await postJSON("/zally/v1/cast-vote", castBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toBeTruthy();
  });

  it("step 14: submit tally with wrong creator is rejected", async () => {
    const tallyBody = makeSubmitTallyPayload(roundId, "zvote1imposter", [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toMatch(/creator/i);
  });

  it("step 15: submit tally finalizes the round", async () => {
    const entries: TallyEntryPayload[] = [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ];
    const tallyBody = makeSubmitTallyPayload(roundId, SESSION_CREATOR, entries);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code, `submit tally rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    await sleep(BLOCK_WAIT_MS);
  });

  it("step 16: round status is FINALIZED after submit tally", async () => {
    const { status, json } = await getJSON(`/zally/v1/round/${roundIdHex}`);

    expect(status).toBe(200);
    expect(json.round).toBeTruthy();
    expect(json.round.status).toBe(SESSION_STATUS.FINALIZED);
  });

  it("step 17: tally is preserved after finalization", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally/${roundIdHex}/0`);

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Same accumulated ciphertext — finalization doesn't alter the tally.
    expect(json.tally["1"]).toBe(fixtures!.expected_accumulated);
  });

  it("step 18: finalized tally results are queryable", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally-results/${roundIdHex}`);

    expect(status).toBe(200);
    expect(json.results).toBeTruthy();
    expect(json.results).toHaveLength(1);
    // Go's encoding/json omits zero-valued fields with omitempty, so
    // proposal_id=0 may be absent (undefined). Use ?? 0 to normalize.
    expect(json.results[0].proposal_id ?? 0).toBe(0);
    expect(json.results[0].vote_decision).toBe(1);
    expect(json.results[0].total_value).toBe(fixtures!.expected_total);
  });

  it("step 19: reveal share rejected after finalization", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
    });
    const { status, json } = await postJSON("/zally/v1/reveal-share", revealBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    // Round is FINALIZED — no further reveals accepted.
    expect(json.log).toBeTruthy();
  });

  it("step 20: submit tally on finalized round is rejected", async () => {
    const tallyBody = makeSubmitTallyPayload(roundId, SESSION_CREATOR, [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    const rejected =
      status !== 200 || (json.code !== undefined && json.code !== 0);
    expect(rejected, `expected rejection but got status=${status} code=${json.code}`).toBe(true);
  });

  it("step 21: submit tally on ACTIVE round is rejected", async () => {
    // Create a fresh long-lived session (default 1h expiry).
    const { body, roundId: activeRoundId } = makeCreateVotingSessionPayload(FIXTURE_EA_PK);
    const createRes = await postJSON("/zally/v1/create-voting-session", body);
    expect(createRes.json.code, `create session rejected: ${createRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // Try to submit tally on the ACTIVE round — should be rejected.
    const tallyBody = makeSubmitTallyPayload(activeRoundId, SESSION_CREATOR, [
      { proposal_id: 0, vote_decision: 0, total_value: 0 },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toMatch(/tallying/i);
  });
}, 600_000); // extended timeout — includes waiting for vote_end_time expiry
