/**
 * End-to-end integration test for the full voting flow.
 *
 * Exercises the complete lifecycle:
 *   1. MsgCreateVotingSession — create a round
 *   2. MsgDelegateVote        — delegate with real RedPallas sig + Halo2 proof (ZKP #1)
 *   3. MsgCastVote            — cast vote with mock proof (ZKP #2)
 *   4. MsgRevealShare         — reveal share with mock proof (ZKP #3)
 *   5. Query tally            — verify accumulated vote
 *   6. MsgSubmitTally         — finalize the session (TALLYING → FINALIZED)
 *
 * ZKP #2 and #3 proofs are mocked: the chain's MockVerifier accepts any bytes
 * in development mode.
 *
 * Prerequisites:
 *   1. Build chain: make install (or make install-ffi for real ZKP #1 verification)
 *   2. Start chain: make init && make start
 *   3. (Optional) Generate fixtures: make fixtures (for real Halo2 proof in delegation)
 */

import { describe, it, expect, beforeAll } from "vitest";
import {
  makeCreateVotingSessionPayload,
  makeDelegateVotePayload,
  makeCastVotePayload,
  makeRevealSharePayload,
  makeSubmitTallyPayload,
  postJSON,
  getJSON,
  sleep,
  BLOCK_WAIT_MS,
  toHex,
  getElGamalFixtures,
  runTreeCli,
  BASE_URL,
  type TallyEntryPayload,
} from "./helpers.js";

// ---------------------------------------------------------------------------
// Helper: poll until a round reaches the expected status (integer enum value).
// ---------------------------------------------------------------------------

/** SessionStatus enum values (protobuf int32 serialized by encoding/json). */
const SESSION_STATUS = {
  UNSPECIFIED: 0,
  ACTIVE: 1,
  TALLYING: 2,
  FINALIZED: 3,
} as const;

/**
 * Poll GET /zally/v1/round/{roundIdHex} until the round reaches `expected`
 * status, or throw after `timeoutMs`.
 */
async function waitForRoundStatus(
  roundIdHex: string,
  expected: number,
  timeoutMs = 90_000,
  intervalMs = 3_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const { json } = await getJSON(`/zally/v1/round/${roundIdHex}`);
    if (json.round?.status === expected) return;
    await sleep(intervalMs);
  }
  throw new Error(
    `Timed out waiting for round ${roundIdHex} to reach status ${expected}`,
  );
}

// ---------------------------------------------------------------------------
// Load ElGamal fixtures once (deterministic — generated by Go).
// ---------------------------------------------------------------------------

const fixtures = getElGamalFixtures();
if (!fixtures) {
  throw new Error(
    "ElGamal fixtures not found. Run: go test -run TestGenerateElGamalFixtures ./crypto/elgamal/",
  );
}
const FIXTURE_EA_PK = new Uint8Array(Buffer.from(fixtures.ea_pk, "base64"));

// ===========================================================================
// Suite 1: Voting flow (long-lived session — no tallying)
// ===========================================================================

describe("E2E Voting Flow", () => {
  // Shared state across sequential test steps.
  let roundId: Uint8Array;
  let roundIdHex: string;
  let anchorHeight: number;

  // -------------------------------------------------------------------------
  // Step 1: Create voting session
  // -------------------------------------------------------------------------

  beforeAll(async () => {
    const { body, roundId: rid } = makeCreateVotingSessionPayload(FIXTURE_EA_PK);
    roundId = rid;
    roundIdHex = toHex(roundId);

    const res = await postJSON("/zally/v1/create-voting-session", body);
    expect(res.json.code, `create session rejected: ${res.json.log}`).toBe(0);

    // Wait for the session creation tx to be included in a block.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 2: Delegate vote (ZKP #1 — real RedPallas sig + Halo2 proof)
  // -------------------------------------------------------------------------

  it("step 1: delegate vote succeeds", async () => {
    const delegationBody = makeDelegateVotePayload(roundId);
    const { status, json } = await postJSON(
      "/zally/v1/delegate-vote",
      delegationBody,
    );

    expect(status).toBe(200);
    expect(json.code, `delegation rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for delegation tx to be included — EndBlocker computes tree root.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 2: Query commitment tree for anchor height (derisk: root, next_index)
  // -------------------------------------------------------------------------

  it("step 2: commitment tree has a computed root after delegation", async () => {
    const { status, json } = await getJSON(
      "/zally/v1/commitment-tree/latest",
    );

    expect(status).toBe(200);
    expect(json.tree).toBeTruthy();
    expect(json.tree.height).toBeGreaterThan(0);
    // DelegateVote appends 2 leaves: cmx_new, gov_comm.
    expect(json.tree.next_index).toBe(2);
    // Root is computed by EndBlocker (Poseidon or placeholder); must be present and 32 bytes.
    expect(json.tree.root).toBeTruthy();
    const rootBytes = Buffer.from(json.tree.root, "base64");
    expect(rootBytes.length).toBe(32);

    // Save anchor height for CastVote and RevealShare.
    anchorHeight = json.tree.height;
  });

  it("step 2b: commitment tree at anchor height returns same root and next_index", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/commitment-tree/${anchorHeight}`,
    );

    expect(status).toBe(200);
    expect(json.tree).toBeTruthy();
    expect(json.tree.height).toBe(anchorHeight);
    expect(json.tree.next_index).toBe(2);
    expect(json.tree.root).toBeTruthy();
    expect(Buffer.from(json.tree.root, "base64").length).toBe(32);
  });

  // -------------------------------------------------------------------------
  // Step 2c: Rust TreeClient sync — independently reconstructs the same root
  // -------------------------------------------------------------------------

  it("step 2c: Rust tree client sync matches chain root (2 leaves)", () => {
    const output = runTreeCli(["sync", "--node", BASE_URL]);

    expect(output).toContain("leaves synced:     2");
    expect(output).toContain("root match:");
    expect(output).toContain("OK");
  }, 120_000); // generous timeout for first cargo build

  // -------------------------------------------------------------------------
  // Step 2d: Witness generation for first VAN leaf (position 0)
  // -------------------------------------------------------------------------

  it("step 2d: witness for first VAN leaf (position 0) verifies", () => {
    const output = runTreeCli([
      "witness", "--node", BASE_URL, "--position", "0",
    ]);

    expect(output).toContain("Witness (hex):");
    expect(output).toContain("Witness size:  772 bytes");
    expect(output).toContain("Anchor root:");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 4: Cast vote (ZKP #2 — mock proof)
  // -------------------------------------------------------------------------

  it("step 3: cast vote succeeds with mock proof", async () => {
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const { status, json } = await postJSON(
      "/zally/v1/cast-vote",
      castBody,
    );

    expect(status).toBe(200);
    expect(json.code, `cast vote rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for cast-vote tx to be included — EndBlocker updates tree root.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 5: Query updated commitment tree for reveal anchor (derisk: next_index, root)
  // -------------------------------------------------------------------------

  it("step 4: commitment tree updated after cast vote", async () => {
    const { status, json } = await getJSON(
      "/zally/v1/commitment-tree/latest",
    );

    expect(status).toBe(200);
    expect(json.tree).toBeTruthy();
    expect(json.tree.height).toBeGreaterThanOrEqual(anchorHeight);
    // CastVote appends 2 leaves: vote_authority_note_new, vote_commitment. Total 4.
    expect(json.tree.next_index).toBe(4);
    expect(json.tree.root).toBeTruthy();
    expect(Buffer.from(json.tree.root, "base64").length).toBe(32);

    // Update anchor height for RevealShare.
    anchorHeight = json.tree.height;
  });

  it("step 4b: commitment leaves API returns blocks with correct leaf counts", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/commitment-tree/leaves?from_height=1&to_height=${anchorHeight}`,
    );

    expect(status).toBe(200);
    expect(json.blocks).toBeDefined();
    expect(Array.isArray(json.blocks)).toBe(true);
    // Delegate block: 2 leaves; cast block: 2 leaves.
    const totalLeaves = json.blocks.reduce(
      (sum: number, b: { leaves?: unknown[] }) => sum + (b.leaves?.length ?? 0),
      0,
    );
    expect(totalLeaves).toBe(4);
    // Each block has height, start_index, leaves; each leaf is 32 bytes (base64).
    // start_index may be omitted when 0 (proto3 omitempty).
    let expectedStart = 0;
    for (const block of json.blocks) {
      expect(block.height).toBeGreaterThan(0);
      expect(block.start_index ?? 0).toBe(expectedStart);
      expect(block.leaves).toBeDefined();
      expect(Array.isArray(block.leaves)).toBe(true);
      for (const leaf of block.leaves) {
        expect(Buffer.from(leaf, "base64").length).toBe(32);
      }
      expectedStart += block.leaves.length;
    }
  });

  // -------------------------------------------------------------------------
  // Step 4c: Rust TreeClient sync — root still matches after cast-vote growth
  // -------------------------------------------------------------------------

  it("step 4c: Rust tree client sync matches chain root (4 leaves)", () => {
    const output = runTreeCli(["sync", "--node", BASE_URL]);

    expect(output).toContain("leaves synced:     4");
    expect(output).toContain("root match:");
    expect(output).toContain("OK");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 4d: Witness for VAN at position 2 (appended by CastVote)
  // -------------------------------------------------------------------------

  it("step 4d: witness for cast-vote VAN leaf (position 2) verifies", () => {
    const output = runTreeCli([
      "witness", "--node", BASE_URL, "--position", "2",
    ]);

    expect(output).toContain("Witness (hex):");
    expect(output).toContain("Witness size:  772 bytes");
    expect(output).toContain("Anchor root:");
  }, 120_000);

  // -------------------------------------------------------------------------
  // Step 6: Reveal share (ZKP #3 — mock proof)
  // -------------------------------------------------------------------------

  it("step 5: reveal share succeeds with mock proof", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
    });
    const { status, json } = await postJSON(
      "/zally/v1/reveal-share",
      revealBody,
    );

    expect(status).toBe(200);
    expect(json.code, `reveal share rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    // Wait for reveal tx to be included.
    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 7: Query tally and verify accumulated vote
  // -------------------------------------------------------------------------

  it("step 6: tally reflects the revealed vote as encrypted ciphertext", async () => {
    const { status, json } = await getJSON(
      `/zally/v1/tally/${roundIdHex}/0`,
    );

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Decision 1 should have an accumulated ciphertext (base64 string, 64 bytes).
    expect(json.tally["1"]).toBeTruthy();
    expect(typeof json.tally["1"]).toBe("string"); // base64-encoded bytes
  });

  // -------------------------------------------------------------------------
  // Negative paths: duplicate nullifier rejection
  // -------------------------------------------------------------------------

  it("step 7: duplicate cast-vote nullifier is rejected", async () => {
    // Build a cast-vote payload with the same structure — but the chain
    // already recorded the previous van_nullifier. We need to reuse the
    // exact same nullifier to trigger rejection, so we build manually.
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const res1 = await postJSON("/zally/v1/cast-vote", castBody);
    expect(res1.json.code, `first cast should succeed: ${res1.json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);

    // Resubmit with the SAME van_nullifier — should be rejected.
    const duplicate = { ...makeCastVotePayload(roundId, anchorHeight) };
    duplicate.van_nullifier = castBody.van_nullifier;

    const res2 = await postJSON("/zally/v1/cast-vote", duplicate);
    expect(res2.status).toBe(200);
    expect(res2.json.code).not.toBe(0);
    expect(res2.json.log).toMatch(/nullifier/i);
  });

  it("step 8: duplicate reveal-share nullifier is rejected", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
    });
    const res1 = await postJSON("/zally/v1/reveal-share", revealBody);
    expect(res1.json.code, `first reveal should succeed: ${res1.json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);

    // Resubmit with the SAME share_nullifier — should be rejected.
    const duplicate = { ...makeRevealSharePayload(roundId, anchorHeight) };
    duplicate.share_nullifier = revealBody.share_nullifier;

    const res2 = await postJSON("/zally/v1/reveal-share", duplicate);
    // The chain rejects the duplicate nullifier. Depending on how the error
    // surfaces through BroadcastTxSync, the API may return either:
    //   a) HTTP 200 with json.code != 0  (ante rejection in CheckTx response)
    //   b) HTTP 502 with an error body   (broadcast-level error)
    const rejected =
      res2.status !== 200 || (res2.json.code !== undefined && res2.json.code !== 0);
    expect(rejected, `expected rejection but got status=${res2.status} code=${res2.json.code}`).toBe(true);
  });
});

// ===========================================================================
// Suite 2: Tallying & finalization lifecycle
//
// Uses a short-lived session (30s expiry) so the EndBlocker transitions
// the round from ACTIVE → TALLYING within the test timeout.
// ===========================================================================

describe("E2E Tallying Lifecycle", () => {
  const SESSION_CREATOR = "zvote1admin";
  const SHORT_EXPIRY_SEC = 30; // session expires 30s after creation

  let roundId: Uint8Array;
  let roundIdHex: string;
  let anchorHeight: number;

  // -------------------------------------------------------------------------
  // Setup: create a short-lived session with the fixture EA public key, run
  // through the voting flow, wait for EndBlocker to transition ACTIVE → TALLYING.
  // -------------------------------------------------------------------------

  beforeAll(async () => {
    // 1. Create session with short expiry AND fixture EA public key.
    const { body, roundId: rid } = makeCreateVotingSessionPayload(FIXTURE_EA_PK, {
      expiresInSec: SHORT_EXPIRY_SEC,
    });
    roundId = rid;
    roundIdHex = toHex(roundId);

    const createRes = await postJSON("/zally/v1/create-voting-session", body);
    expect(createRes.json.code, `create session rejected: ${createRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // 2. Delegate vote
    const delegationBody = makeDelegateVotePayload(roundId);
    const delRes = await postJSON("/zally/v1/delegate-vote", delegationBody);
    expect(delRes.json.code, `delegation rejected: ${delRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // 3. Get anchor height
    const treeRes = await getJSON("/zally/v1/commitment-tree/latest");
    expect(treeRes.json.tree).toBeTruthy();
    anchorHeight = treeRes.json.tree.height;

    // 4. Cast vote
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const castRes = await postJSON("/zally/v1/cast-vote", castBody);
    expect(castRes.json.code, `cast vote rejected: ${castRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // 5. Update anchor
    const tree2 = await getJSON("/zally/v1/commitment-tree/latest");
    anchorHeight = tree2.json.tree.height;

    // 6. Reveal first share (during ACTIVE phase) — fixture share[0].
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
      encShare: fixtures.shares[0].enc_share,
    });
    const revealRes = await postJSON("/zally/v1/reveal-share", revealBody);
    expect(revealRes.json.code, `reveal share rejected: ${revealRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // 7. Wait for the round to transition to TALLYING (EndBlocker fires once
    //    blockTime >= vote_end_time).
    await waitForRoundStatus(roundIdHex, SESSION_STATUS.TALLYING);
  }, 120_000); // generous timeout for beforeAll

  // -------------------------------------------------------------------------
  // Step 1: Round is confirmed TALLYING
  // -------------------------------------------------------------------------

  it("step 1: round status is TALLYING after expiry", async () => {
    const { status, json } = await getJSON(`/zally/v1/round/${roundIdHex}`);

    expect(status).toBe(200);
    expect(json.round).toBeTruthy();
    expect(json.round.status).toBe(SESSION_STATUS.TALLYING);
  });

  // -------------------------------------------------------------------------
  // Step 2: Reveals still accepted during TALLYING
  // -------------------------------------------------------------------------

  it("step 2: reveal share succeeds during TALLYING", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
      encShare: fixtures!.shares[1].enc_share,
    });
    const { status, json } = await postJSON("/zally/v1/reveal-share", revealBody);

    expect(status).toBe(200);
    expect(json.code, `reveal during TALLYING rejected: ${json.log}`).toBe(0);

    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 3: Tally reflects all accumulated reveals
  // -------------------------------------------------------------------------

  it("step 3: accumulated tally matches Go-computed HomomorphicAdd", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally/${roundIdHex}/0`);

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Decision 1 should have an accumulated ciphertext (from two reveals).
    expect(json.tally["1"]).toBeTruthy();
    expect(typeof json.tally["1"]).toBe("string"); // base64-encoded ciphertext

    // The on-chain HomomorphicAdd(share[0], share[1]) should produce the
    // exact same ciphertext bytes as the Go-computed expected_accumulated.
    expect(json.tally["1"]).toBe(fixtures!.expected_accumulated);
  });

  // -------------------------------------------------------------------------
  // Step 4: Delegations rejected during TALLYING
  // -------------------------------------------------------------------------

  it("step 4: delegate vote rejected during TALLYING", async () => {
    const delegationBody = makeDelegateVotePayload(roundId);
    const { status, json } = await postJSON("/zally/v1/delegate-vote", delegationBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    // The ante handler rejects non-ACTIVE messages for delegation.
    expect(json.log).toBeTruthy();
  });

  // -------------------------------------------------------------------------
  // Step 5: Cast vote rejected during TALLYING
  // -------------------------------------------------------------------------

  it("step 5: cast vote rejected during TALLYING", async () => {
    const castBody = makeCastVotePayload(roundId, anchorHeight);
    const { status, json } = await postJSON("/zally/v1/cast-vote", castBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toBeTruthy();
  });

  // -------------------------------------------------------------------------
  // Step 6: Submit tally with wrong creator is rejected
  // -------------------------------------------------------------------------

  it("step 6: submit tally with wrong creator is rejected", async () => {
    // Entries are included (required), but creator mismatch triggers first.
    const tallyBody = makeSubmitTallyPayload(roundId, "zvote1imposter", [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toMatch(/creator/i);
  });

  // -------------------------------------------------------------------------
  // Step 7: Submit tally by correct creator succeeds
  // -------------------------------------------------------------------------

  it("step 7: submit tally finalizes the round", async () => {
    // Entries contain the EA-claimed plaintext totals per (proposal, decision).
    // With DLEQ stubbed, any value is accepted — but we use the real sum.
    const entries: TallyEntryPayload[] = [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ];
    const tallyBody = makeSubmitTallyPayload(roundId, SESSION_CREATOR, entries);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code, `submit tally rejected: ${json.log}`).toBe(0);
    expect(json.tx_hash).toBeTruthy();

    await sleep(BLOCK_WAIT_MS);
  });

  // -------------------------------------------------------------------------
  // Step 8: Round status is FINALIZED
  // -------------------------------------------------------------------------

  it("step 8: round status is FINALIZED after submit tally", async () => {
    const { status, json } = await getJSON(`/zally/v1/round/${roundIdHex}`);

    expect(status).toBe(200);
    expect(json.round).toBeTruthy();
    expect(json.round.status).toBe(SESSION_STATUS.FINALIZED);
  });

  // -------------------------------------------------------------------------
  // Step 9: Tally preserved after finalization
  // -------------------------------------------------------------------------

  it("step 9: tally is preserved after finalization", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally/${roundIdHex}/0`);

    expect(status).toBe(200);
    expect(json.tally).toBeTruthy();
    // Same accumulated ciphertext as step 3 — finalization doesn't alter the tally.
    expect(json.tally["1"]).toBe(fixtures!.expected_accumulated);
  });

  // -------------------------------------------------------------------------
  // Step 9b: Finalized tally results are queryable via /tally-results
  // -------------------------------------------------------------------------

  it("step 9b: finalized tally results are queryable", async () => {
    const { status, json } = await getJSON(`/zally/v1/tally-results/${roundIdHex}`);

    expect(status).toBe(200);
    expect(json.results).toBeTruthy();
    expect(json.results).toHaveLength(1);
    // Go's encoding/json omits zero-valued fields with omitempty, so
    // proposal_id=0 may be absent (undefined). Use ?? 0 to normalize.
    expect(json.results[0].proposal_id ?? 0).toBe(0);
    expect(json.results[0].vote_decision).toBe(1);
    expect(json.results[0].total_value).toBe(fixtures!.expected_total);
  });

  // -------------------------------------------------------------------------
  // Step 10: Reveals rejected after FINALIZED
  // -------------------------------------------------------------------------

  it("step 10: reveal share rejected after finalization", async () => {
    const revealBody = makeRevealSharePayload(roundId, anchorHeight, {
      proposalId: 0,
      voteDecision: 1,
    });
    const { status, json } = await postJSON("/zally/v1/reveal-share", revealBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    // Round is FINALIZED — no further reveals accepted.
    expect(json.log).toBeTruthy();
  });

  // -------------------------------------------------------------------------
  // Step 11: Submit tally again is rejected (already finalized)
  // -------------------------------------------------------------------------

  it("step 11: submit tally on finalized round is rejected", async () => {
    const tallyBody = makeSubmitTallyPayload(roundId, SESSION_CREATOR, [
      { proposal_id: 0, vote_decision: 1, total_value: fixtures!.expected_total },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    // The chain rejects the tx because the round is FINALIZED, not TALLYING.
    // Depending on how the error surfaces through BroadcastTxSync, the API
    // may return either:
    //   a) HTTP 200 with json.code != 0  (ante rejection in CheckTx response)
    //   b) HTTP 502 with an error body   (broadcast-level error)
    const rejected =
      status !== 200 || (json.code !== undefined && json.code !== 0);
    expect(rejected, `expected rejection but got status=${status} code=${json.code}`).toBe(true);
  });

  // -------------------------------------------------------------------------
  // Step 12: Submit tally on an ACTIVE round is rejected
  // -------------------------------------------------------------------------

  it("step 12: submit tally on ACTIVE round is rejected", async () => {
    // Create a fresh long-lived session (default 1h expiry).
    const { body, roundId: activeRoundId } = makeCreateVotingSessionPayload(FIXTURE_EA_PK);
    const createRes = await postJSON("/zally/v1/create-voting-session", body);
    expect(createRes.json.code, `create session rejected: ${createRes.json.log}`).toBe(0);
    await sleep(BLOCK_WAIT_MS);

    // Try to submit tally on the ACTIVE round — should be rejected.
    const tallyBody = makeSubmitTallyPayload(activeRoundId, SESSION_CREATOR, [
      { proposal_id: 0, vote_decision: 0, total_value: 0 },
    ]);
    const { status, json } = await postJSON("/zally/v1/submit-tally", tallyBody);

    expect(status).toBe(200);
    expect(json.code).not.toBe(0);
    expect(json.log).toMatch(/tallying/i);
  });
}, 180_000); // extended timeout for the tallying suite (includes waiting for expiry)
